version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
