version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=taktodoi_db
